### ISSUE TITLE
Automapper issue

### ISSUE THREAD

**Issue by r3vr0ck** [dlmelendez/identityserver4-azurestorage#22] opened 2021-01-29 14:13 UTC
Currently facing issue with a mapping exception:
Method not found: '!!0 AutoMapper.IMapper.Map(System.Object)'.
System.MissingMethodException: Method not found: '!!0 AutoMapper.IMapper.Map(System.Object)'. ToEntity(...
Any plan to support the newest version of Automapper?
I'm asking this because I had to pull down the sources and update Automapper to 10.1.1 version to make it work in my solution.
Thanks a lot.

**Comment by dlmelendez** [comment] 2021-02-25 03:38
duplicate of #21

**Closed as completed by dlmelendez** 2021-02-25 03:38 UTC
Labels: bug, duplicate
